### ISSUE TITLE
Architecture for the service binding spec compatible readers

### ISSUE THREAD

**Issue by wtrocki** [nodeshift/kube-service-bindings#1]
I think that library to be useful needs to work on 3 different layers:

1) Mapping filesystem into JavaScript objects (volume is based on secret so it is guaranteed that each file content is always string type

2) Mapping based on SB type - if type kafka we can build recognizable configs

3) Decoration for end user specific library and authentication (this is currently done but technically it could be done in the end user app or example especially that we look to promote single library for kafka and others.

![Screenshot 2021-04-14 at 09 46 27](https://user-images.githubusercontent.com/981838/114681764-5cf72f00-9d06-11eb-9be5-ff8a4d76034d.png)

**Comment by mhdawson** [comment]
I think that is a good picture of what is there!. 

services['KAFKA'].type holds the type that we look for in the /bindings/X/type file, were X is each of the directories under /bindings until a match is found.

services['KAFKA'].clients then holds the "knownTypeTransformers" to project to a specific client library.  I hope you don't mind if you borrow that picture for the doc I'm working on :)

**Comment by wtrocki** [comment]
Amazing. Good to close then

**Comment by mhdawson** [comment]
+1 on those suggestions.  Once we validate we have it working I'll spin out some tasks to extend.
