### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by mhdawson** [nodeshift/kube-service-bindings#66]
@pacostas I'm thinking that we should probably do a release to expose the recent PRs.

Do you think we should do that before/after we land https://github.com/nodeshift/kube-service-bindings/pull/60 and are there any other changes that you think we should do before that?

**Comment by pacostas** [comment]
@mhdawson Yes I agree. Despite https://github.com/nodeshift/kube-service-bindings/pull/60 does not introduce any breaking changes, we still need some time to discuss/review the extra functionality, so +1 to release and merge https://github.com/nodeshift/kube-service-bindings/pull/60 later

**Comment by pacostas** [comment]
Yes, I agree doing a release now. The https://github.com/nodeshift/kube-service-bindings/pull/60 does not have any breaking changes only adds extra functionality that does not affect previous versions so a minor version for https://github.com/nodeshift/kube-service-bindings/pull/60 would make sense.

**Comment by mhdawson** [comment]
Published 2.0.0 - https://www.npmjs.com/package/kube-service-bindings/v/2.0.0
