### ISSUE TITLE
Support provider based lookup

### ISSUE THREAD

**Issue by baijum** [nodeshift/kube-service-bindings#7]
It is possible to have different providers for the same type. For example, if the type is `mysql`, the providers could be `mariadb` or `oracle`.

I was exploring how an API should look in different languages:
https://github.com/k8s-service-bindings/spec/issues/174

I think it's a bit difficult to standardize across languages and frameworks. But the API can follow certain patterns.
Looking forward to your thoughts.

**Comment by mhdawson** [comment]
@baijum thanks for the question. The API already has the `client` parameter which allows for different results based on the needs of the client. In the case of the example you show I see there are different clients in npm (mariadb and oracledb) and you would use (if implemented):

serviceBindings.getBinding('MYSQL', 'mariadb');

or

serviceBindings.getBinding('MYSQL', 'oracledb');

with the existing API.  So while the naming might not line up with `provider`, it may cover the use case.

**Comment by baijum** [comment]
@mhdawson Thanks for the clarification.

I am closing the issue.
